import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { ErrorState, LoadingState } from '../../../components/ui/ContentState.jsx';
import { usePageTitle } from '../../../hooks/usePageTitle.js';
import QuizQuestion from '../../quizzes/components/QuizQuestion.jsx';
import { getHskMockAttempt, submitHskMockAttempt } from '../services/hskExamService.js';
import '../../quizzes/styles/quiz.css';
import '../styles/hsk-exams.css';

function answerText(item) { if (item.correctAnswer?.content) return item.correctAnswer.content; if (item.correctAnswer?.acceptedAnswers) return item.correctAnswer.acceptedAnswers.join(' / '); return item.correctAnswer?.tokens?.map((token) => token.content).join(' ') || ''; }

export default function HskMockAttemptPage() {
  const { attemptId } = useParams(); const location = useLocation();
  const [attempt, setAttempt] = useState(location.state?.attempt || null); const [answers, setAnswers] = useState({}); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const [remaining, setRemaining] = useState(0);
  usePageTitle(attempt?.exam?.title || 'Thi thử HSK');
  const load = useCallback((signal) => getHskMockAttempt(attemptId, { signal }).then((response) => setAttempt(response.data)).catch((caught) => { if (caught.name !== 'AbortError') setError(caught.message); }), [attemptId]);
  useEffect(() => { if (attempt) return undefined; const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [attempt, load]);
  useEffect(() => { if (!attempt?.expiresAt || attempt.status !== 'in_progress') return undefined; const tick = () => setRemaining(Math.max(0, Math.ceil((new Date(attempt.expiresAt).getTime() - Date.now()) / 1000))); tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer); }, [attempt]);
  const answered = useMemo(() => Object.keys(answers).length, [answers]);
  async function submit(event) { event.preventDefault(); setSubmitting(true); setError(''); try { const payload = Object.entries(answers).map(([questionId, answer]) => ({ questionId, answer })); const response = await submitHskMockAttempt(attempt.id, payload); setAttempt({ ...response.data, exam: attempt.exam }); } catch (caught) { setError(caught.message); } finally { setSubmitting(false); } }
  if (!attempt && !error) return <section className="quiz-page"><div className="public-container"><LoadingState label="Đang mở bài thi" /></div></section>;
  if (!attempt) return <section className="quiz-page"><div className="public-container"><ErrorState message={error} onRetry={() => load()} /></div></section>;
  if (attempt.status === 'submitted') return <ExamResult attempt={attempt} />;
  return <section className="quiz-page hsk-attempt-page"><div className="public-container quiz-page__inner"><header className="quiz-page__header"><p className="public-eyebrow">HSK {attempt.exam.level} · Thi thử</p><h1>{attempt.exam.title}</h1><div className="hsk-attempt-meta"><strong aria-live="polite">{String(Math.floor(remaining / 60)).padStart(2, '0')}:{String(remaining % 60).padStart(2, '0')}</strong><span>{answered}/{attempt.questions.length} câu đã trả lời</span></div><p>Thời điểm bắt đầu và hết giờ được lưu trên máy chủ. Bài này không phải đề thi HSK chính thức.</p></header><form onSubmit={submit}>{attempt.questions.map((question, index) => <div key={question.id}>{question.audioUrl && <audio controls preload="metadata" src={question.audioUrl}>Trình duyệt không hỗ trợ audio.</audio>}{question.imageUrl && <img className="hsk-question-image" src={question.imageUrl} alt="Minh họa câu hỏi" />}<QuizQuestion answer={answers[question.id]} index={index} question={question} onChange={(answer) => setAnswers((current) => ({ ...current, [question.id]: answer }))} /></div>)}{error && <p className="quiz-page__error">{error}</p>}<button className="button button--primary quiz-page__submit" disabled={submitting} type="submit">{submitting ? 'Đang chấm…' : 'Nộp bài'}</button></form></div></section>;
}

function ExamResult({ attempt }) { return <section className="quiz-page"><div className="public-container quiz-page__inner"><div className={`quiz-result ${attempt.passed ? 'is-passed' : 'is-failed'}`}><div className="quiz-result__summary"><p className="public-eyebrow">HSK {attempt.exam.level} · Kết quả thi thử</p><h1>{attempt.score}/100</h1><strong>{attempt.passed ? 'Đạt mục tiêu luyện tập' : 'Chưa đạt mục tiêu luyện tập'}</strong><p>{attempt.correctCount} đúng / {attempt.wrongCount} sai</p></div><div className="hsk-section-scores">{attempt.sectionScores.map((section) => <article key={section.sectionId}><span>{section.title}</span><strong>{section.score}%</strong><small>{section.earnedPoints}/{section.totalPoints} điểm</small></article>)}</div><ul className="hsk-evaluation">{attempt.evaluation.map((item) => <li key={item}>{item}</li>)}</ul><div className="quiz-result__details">{attempt.results.map((item, index) => <article className={item.correct ? 'is-correct' : 'is-incorrect'} key={item.questionId}><header><strong>Câu {index + 1}: {item.question}</strong><span>{item.earnedPoints}/{item.possiblePoints}</span></header><p>{item.correct ? 'Chính xác' : `Đáp án đúng: ${answerText(item)}`}</p>{item.explanation && <small>{item.explanation}</small>}</article>)}</div><div className="quiz-result__actions"><Link className="button button--secondary" to="/hsk-mock-tests">Chọn đề khác</Link><Link className="button button--primary" to={`/hsk-mock-tests/${attempt.examId}/history`}>Lịch sử kết quả</Link></div></div></div></section>; }
