import { useEffect, useState } from 'react';

const fallbackJobs = [
  { id: 'frontend-developer', title: 'Frontend Developer', type: 'Full-time', location: 'Tân Uyên, Bình Dương', description: 'Build reliable digital experiences and internal tools with the SPG team.' },
  { id: 'logistics-coordinator', title: 'Logistics Coordinator', type: 'Full-time', location: 'Tân Uyên, Bình Dương', description: 'Coordinate operations and help our teams deliver consistent results.' },
  { id: 'production-office-staff', title: 'Production Office Staff', type: 'Full-time', location: 'Tân Uyên, Bình Dương', description: 'Support production planning, documentation and cross-team communication.' },
];

function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [jobs, setJobs] = useState(fallbackJobs); const [selectedJob, setSelectedJob] = useState(null); const [form, setForm] = useState({ name: '', email: '', phone: '', message: '' }); const [status, setStatus] = useState('');
  useEffect(() => { fetch('/api/jobs').then((r) => r.json()).then((d) => setJobs(d.data || fallbackJobs)).catch(() => {}); }, []);
  async function submitApplication(e) { e.preventDefault(); setStatus('Đang gửi hồ sơ...'); try { const r = await fetch('/api/applications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, jobId: selectedJob.id }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setStatus('Đã tiếp nhận thông tin ứng tuyển.'); setForm({ name: '', email: '', phone: '', message: '' }); } catch (error) { setStatus(error.message || 'Không thể gửi hồ sơ.'); } }
  return <div className="site-shell"><header className="header"><a className="logo" href="#home">SPG<span>.</span></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)}>☰</button><nav className={menuOpen ? 'nav open' : 'nav'}><a href="#about">Giới thiệu</a><a href="#activities">Hoạt động</a><a href="#careers">Tuyển dụng</a><a href="#contact">Liên hệ</a></nav></header><main>
    <section id="home" className="hero"><div><p className="eyebrow">CÔNG TY TNHH CHÍ HÙNG · SPG</p><h1>Built with<br/><em>purpose.</em></h1><p className="hero-copy">Đồng hành cùng chuỗi giá trị giày thể thao bằng năng lực sản xuất, con người và tinh thần phát triển bền vững.</p><a className="button" href="#about">Khám phá SPG <span>↗</span></a></div><div className="hero-card"><div className="orb">SPG</div><p>Quality. People. Progress.</p></div></section>
    <section id="about" className="section split"><div><p className="eyebrow">VỀ CHÚNG TÔI</p><h2>Chất lượng tạo nên<br/><em>niềm tin.</em></h2></div><div><p>Công ty TNHH Chí Hùng là doanh nghiệp sản xuất giày dép tại Tân Uyên, Bình Dương, thuộc hệ sinh thái SPG. Doanh nghiệp được các nguồn công khai giới thiệu là hoạt động từ năm 2000 trong lĩnh vực giày thể thao và các sản phẩm liên quan.</p><p>Chúng tôi hướng đến môi trường làm việc chuyên nghiệp, an toàn và tôn trọng con người.</p></div></section>
    <section id="activities" className="section activities"><p className="eyebrow">HOẠT ĐỘNG CỦA CHÚNG TÔI</p><h2>From people to<br/><em>performance.</em></h2><div className="activity-grid"><article><span>01</span><h3>Năng lực sản xuất</h3><p>Quy trình, tiêu chuẩn và sự phối hợp tạo nên sản phẩm ổn định.</p></article><article><span>02</span><h3>Con người</h3><p>Phát triển đội ngũ bằng cơ hội học hỏi và môi trường hợp tác.</p></article><article><span>03</span><h3>Cộng đồng</h3><p>Hướng tới những hoạt động tích cực và giá trị lâu dài tại địa phương.</p></article></div></section>
    <section id="careers" className="section careers"><div className="careers-heading"><div><p className="eyebrow">CƠ HỘI NGHỀ NGHIỆP</p><h2>Grow with<br/><em>SPG.</em></h2></div><p>Gia nhập đội ngũ Chí Hùng và cùng tạo nên những giá trị bền vững hơn mỗi ngày.</p></div><div className="job-list">{jobs.map((job) => <article className="job" key={job.id}><div><h3>{job.title}</h3><p>{job.type} · {job.location}</p><small>{job.description}</small></div><button className="apply-button" onClick={() => { setSelectedJob(job); setStatus(''); }}>Ứng tuyển ↗</button></article>)}</div>{selectedJob && <div className="application-card"><button className="close-button" onClick={() => setSelectedJob(null)}>×</button><p className="eyebrow">ỨNG TUYỂN</p><h3>{selectedJob.title}</h3><form onSubmit={submitApplication}><input required placeholder="Họ và tên" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/><input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/><input placeholder="Số điện thoại" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })}/><textarea required placeholder="Giới thiệu ngắn về bạn" rows="4" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })}/><button className="button" type="submit">Gửi hồ sơ</button></form>{status && <p className="form-status">{status}</p>}</div>}</section>
    <section id="contact" className="contact"><p className="eyebrow">LIÊN HỆ</p><h2>Cùng tạo nên<br/><em>điều tốt hơn.</em></h2><p>Khu phố Mỹ Hiệp, phường Thái Hòa, thành phố Tân Uyên, Bình Dương</p><a className="button light" href="mailto:hr@spg-sportsgear.com">Liên hệ với chúng tôi <span>↗</span></a></section></main><footer><span>© 2026 Công ty TNHH Chí Hùng · SPG</span><span>Corporate & Careers</span></footer></div>;
}
export default App;